# Generated by Django 5.2.6 on 2025-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
