# Generated by Django 5.2.6 on 2025-09-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='Specialty',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
