# Generated by Django 5.2.6 on 2025-09-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Specialty',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
