# Generated by Django 5.2.6 on 2025-09-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_rename_specialty_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
