# Generated by Django 5.2.6 on 2025-09-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_rename_speciality_doctor_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='Specialty',
        ),
    ]
