# Generated by Django 5.2.6 on 2025-09-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_rename_name_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
