# Generated by Django 5.2.6 on 2025-09-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0012_rename_doctor_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='Specialty',
            new_name='specialty',
        ),
    ]
