# Generated by Django 5.2.6 on 2025-09-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_rename_name_doctors_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
