# Generated by Django 5.2.6 on 2025-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0017_appointment_date_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='default123', max_length=128),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='karan@123', max_length=15),
            preserve_default=False,
        ),
    ]
