from django.urls import path
from .views import home
from . import views
urlpatterns = [
    path('',home, name="home"),
    path('registraion/',views.registration_detail,name="registration_detail"),
    path('api/register/',views.registration_store,name="register_api"),
    path('patient/login/',views.patient_login,name="patient_login"),
    path('patient/verify',views.patient_verify,name="patient_verify"),
    path('book/appointment/', views.book_appointment, name="book_appointment"),
    path('appointment/success/',views.appointment_success,name="appointment_success"),
    path('status/verify/',views.status_verify,name="status_verify") ,
    path('status/check/',views.status_check,name="status_check"),
    path('status/page/',views.status_page,name="status_page"),
    path('adminpage/dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('adminpage/login/',views.admin_login,name="admin_login"),
    path('adminpage/verify/',views.admin_verify,name="admin_verify"),
    path("adminpage/update_status/<int:appointment_id>/<str:status>/", views.update_status, name="update_status"),
    path("adminpage/home/",views.admin_home,name="admin_home"),
    path("admin/logout/", views.admin_logout, name="admin_logout"),
    path('doctor/add/page/',views.doctor_add_page,name="doctor_add_page"),
    path("delete/doctor/<doctor_id>/",views.delete_doctor,name="delete_doctor"),
    path('manage/doctors/',views.manage_doctors,name="manage_doctors"),
    path('patient/add/page/',views.patient_add_page,name="patient_add_page"),
    path('delete/patient/<patient_id>/',views.delete_patient,name="delete_patient"),
    path('manage/patients/',views.manage_patients,name="manage_patients"),
    path("adminpage/logout/", views.admin_logout, name="admin_logout"),
    path('doctor/login/',views.doctor_login,name="doctor_login"),
    path("doctor/verify/",views.doctor_verify,name="doctor_verify"),
    path("doctor/home/",views.doctor_home,name="doctor_home"),
    path("doctorpage/update_status_doctor/<int:appointment_id>/<str:status>/", views.update_status_doctor, name="update_status_doctor"),
    path('doctor/logout/',views.doctor_logout,name="doctor_logout"),
    path('patient/guide/',views.patient_guide,name="patient_guide"),
]
