from django.urls import path
from .views import home
from . import views

urlpatterns = [
    path('',home, name="home"),
    path('registraion/',views.registration_detail,name="registration_detail"),
    path('api/register/',views.registration_store,name="register_api"),
    path('api/register/done/',views.register_done,name="register_done"),
    path("api/patient/verify/", views.patient_verify_api, name="patient_verify_api"),
    path('patient/login/',views.patient_login,name="patient_login"),
    path('bookappointment/render/',views.book_appointment_render,name="book_appointment_render"),
    path('api/book/appointment/', views.book_appointment, name="book_appointment"),
    path('appointment/success/',views.appointment_success,name="appointment_success"),
    path('status/verify/', views.status_verify, name="status_verify"),
    path('api/status/check/', views.status_check, name="status_check"),
    path('api/status/page/', views.status_page, name="status_page"),
    path("status/dashboard/", views.status_dashboard, name="status_dashboard"),
    path('api/adminpage/dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('adminpage/login/',views.admin_login,name="admin_login"),
    path('adminpage/verify/',views.admin_verify,name="admin_verify"),
    path("adminpage/update_status/<int:appointment_id>/<str:status>/", views.update_status, name="update_status"),
    path('adminpage/dasboard',views.adminpage_show,name="adminpage_show"),
    path("adminpage/home/",views.admin_home,name="admin_home"),
    path("admin/logout/", views.admin_logout, name="admin_logout"),
    path('doctor/add/page/',views.doctor_add_page,name="doctor_add_page"),
    path("delete/doctor/<doctor_id>/",views.delete_doctor,name="delete_doctor"),
    path('manage/doctors/',views.manage_doctors,name="manage_doctors"),
    path("adminpage/home/", views.admin_home_page, name="admin_home_page"),
    path("patient/adminpage",views.patient_adminpage,name="patient_adminpage"),
    path("api/patients/",views.manage_patient_api,name="manage_patient"),
    path("api/patients/<int:pk>/",views.delete_patient_api,name="delete_patient_api,"),
    path("adminpage/logout/", views.admin_logout, name="admin_logout"),
    path('doctor/login/',views.doctor_login,name="doctor_login"),
    path("doctor/verify/",views.doctor_verify,name="doctor_verify"),
    path("doctor/home/",views.doctor_home,name="doctor_home"),
    path("doctorpage/update_status_doctor/<int:appointment_id>/<str:status>/", views.update_status_doctor, name="update_status_doctor"),
    path('doctor/logout/',views.doctor_logout,name="doctor_logout"),
    path('patient/guide/',views.patient_guide,name="patient_guide"),
]
